server:
  port: ${PORT:4173}
  address: 0.0.0.0
  compression:
    enabled: true
  servlet:
    session:
      cookie:
        http-only: true
spring:
  application:
    name: gptnet-image
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 32MB
  data:
    redis:
      url: ${REDIS_URL:redis://127.0.0.1:6379}
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:50}
  web:
    resources:
      static-locations:
        - file:public/
management:
  endpoints:
    enabled-by-default: false
